# Generated by Django 5.2.7 on 2025-10-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('POKEMON', 'Pokémon'), ('MAGIC', 'Magic: The Gathering'), ('YUGIOH', 'Yu-Gi-Oh'), ('ACESSORIO', 'Acessório')], max_length=20, unique=True),
        ),
    ]
