# Generated by Django 5.2.7 on 2025-10-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg', '0002_alter_categoria_descricao_alter_categoria_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='carta',
            name='condicao',
            field=models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('POKEMON', 'Pokémon'), ('MAGIC', 'Magic: The Gathering'), ('YUGIOH', 'Yu-Gi-Oh')], max_length=20, unique=True),
        ),
    ]
